#!/usr/bin/env bash

cd /var/www/html || exit

echo "连接存储目录..."

php artisan storage:link || exit

echo "开始动态编译前端资源..."

if [ -f package-lock.json ]; then \
    npm run build; \
elif [ -f yarn.lock ]; then \
    corepack enable yarn && yarn build; \
elif [ -f pnpm-lock.yaml ]; then \
    corepack enable pnpm && pnpm build; \
else \
    echo "No lockfile found." && exit 1; \
fi

echo "前端资源编译完成！"

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
