# docker/supervisord.conf
[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/var/run/supervisord.pid

# ==================== 主服务 ====================
[program:octane]
command=php artisan octane:frankenphp --host=0.0.0.0
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile_backups=0
stdout_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
priority=1

# ==================== Reverb ====================
[program:reverb]
command=php artisan reverb:start --host=0.0.0.0 --port=8080
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile_backups=0
stdout_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
priority=2

# ==================== Queue ====================
[program:queue]
command=php artisan queue:work --sleep=3 --tries=3 --max-time=3600
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
priority=3

# ==================== Schedule ====================
[program:scheduler]
command=php artisan schedule:work
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile_backups=0
stdout_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
priority=4

# ==================== Pulse ====================
[program:scheduler]
command=php artisan pulse:check
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile_backups=0
stdout_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
priority=4
